/*
- Copyright (C) 2026 Ilkka Lehtoranta
- SPDX-License-Identifier: MIT
*/

// Generated by CopperOS/tools/MuiInventory/generate_csharp_vector_tests.py.
// Public identifiers and fixed-width ABI facts only.

using System.Reflection;
using Amiga;
using CopperSharp.Compiler;
using CopperSharp.Sdk.Amiga;
using Xunit;

namespace CopperSharp.Compiler.Tests;

public sealed class MuiVectorAbiTests
{
	[Fact]
	public void EveryPublicVectorHasExactLvoAndRegisters()
	{
		Vector(nameof(MUIMaster.MUI_BeginRefresh), -192, M68kRegister.A0, M68kRegister.D0);
		Vector(nameof(MUIMaster.MUI_EndRefresh), -198, M68kRegister.A0, M68kRegister.D0);
		Vector(nameof(MUIMaster.MUI_DisposeObject), -36, M68kRegister.A0);
		Vector(nameof(MUIMaster.MUI_Redraw), -102, M68kRegister.A0, M68kRegister.D0);
		Vector(nameof(MUIMaster.MUI_GetClass), -78, M68kRegister.A0);
		Vector(nameof(MUIMaster.MUI_AddClipping), -168, M68kRegister.A0, M68kRegister.D0, M68kRegister.D1, M68kRegister.D2, M68kRegister.D3);
		Vector(nameof(MUIMaster.MUI_FreeClass), -84, M68kRegister.A0);
		Vector(nameof(MUIMaster.MUI_AddClipRegion), -180, M68kRegister.A0, M68kRegister.A1);
		Vector(nameof(MUIMaster.MUI_CreateCustomClass), -108, M68kRegister.A0, M68kRegister.A1, M68kRegister.A2, M68kRegister.D0, M68kRegister.A3);
		Vector(nameof(MUIMaster.MUI_DeleteCustomClass), -114, M68kRegister.A0);
		Vector(nameof(MUIMaster.MUI_MakeObjectA), -120, M68kRegister.D0, M68kRegister.A0);
		Vector(nameof(MUIMaster.MUI_NewObjectA), -30, M68kRegister.A0, M68kRegister.A1);
		Vector(nameof(MUIMaster.MUI_RemoveClipRegion), -186, M68kRegister.A0, M68kRegister.A1);
		Vector(nameof(MUIMaster.MUI_RequestA), -42, M68kRegister.D0, M68kRegister.D1, M68kRegister.D2, M68kRegister.A0, M68kRegister.A1, M68kRegister.A2, M68kRegister.A3);
		Vector(nameof(MUIMaster.MUI_RejectIDCMP), -96, M68kRegister.A0, M68kRegister.D0);
		Vector(nameof(MUIMaster.MUI_SetError), -72, M68kRegister.D0);
		Vector(nameof(MUIMaster.MUI_RequestIDCMP), -90, M68kRegister.A0, M68kRegister.D0);
		Vector(nameof(MUIMaster.MUI_AslRequest), -54, M68kRegister.A0, M68kRegister.A1);
		Vector(nameof(MUIMaster.MUI_ReleasePen), -162, M68kRegister.A0, M68kRegister.D0);
		Vector(nameof(MUIMaster.MUI_Error), -66);
		Vector(nameof(MUIMaster.MUI_FreeAslRequest), -60, M68kRegister.A0);
		Vector(nameof(MUIMaster.MUI_ObtainPen), -156, M68kRegister.A0, M68kRegister.A1, M68kRegister.D0);
		Vector(nameof(MUIMaster.MUI_Layout), -126, M68kRegister.A0, M68kRegister.D0, M68kRegister.D1, M68kRegister.D2, M68kRegister.D3, M68kRegister.D4);
		Vector(nameof(MUIMaster.MUI_GetRGBColor), -690, M68kRegister.A0, M68kRegister.A1, M68kRegister.A2);
		Vector(nameof(MUIMaster.MUI_AllocAslRequest), -48, M68kRegister.D0, M68kRegister.A0);
		Vector(nameof(MUIMaster.MUI_RemoveClipping), -174, M68kRegister.A0, M68kRegister.A1);
		Vector(nameof(MUIMaster.MUI_RequestObjectA), -756, M68kRegister.D0, M68kRegister.D1, M68kRegister.D2, M68kRegister.A0, M68kRegister.A1, M68kRegister.A2, M68kRegister.A3, M68kRegister.A4);
	}

	private static void Vector(string name, int lvo, params M68kRegister[] registers)
	{
		var method = typeof(MUIMaster).GetMethod(name, BindingFlags.Public | BindingFlags.Static);
		Assert.NotNull(method);
		Assert.Equal(lvo, method!.GetCustomAttribute<AmigaLvoAttribute>()?.Offset);
		var parameters = method.GetParameters();
		Assert.Equal(registers.Length, parameters.Length);
		for (var index = 0; index < parameters.Length; index++)
			Assert.Equal(registers[index], parameters[index].GetCustomAttribute<M68kRegisterAttribute>()?.Register);
		if (method.ReturnType != typeof(void))
			Assert.Equal(M68kRegister.D0, method.ReturnParameter.GetCustomAttribute<M68kRegisterAttribute>()?.Register);
	}
}
