/*
- Copyright (C) 2026 Ilkka Lehtoranta
- SPDX-License-Identifier: MIT
*/

// Generated by CopperOS/tools/MuiInventory/generate_csharp_messages.py.
// Public identifiers and fixed-width ABI facts only.

using System.Runtime.InteropServices;

namespace Amiga.MUI;

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_CallHook
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR Hook;
	public uint param1;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Export
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR dataspace;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_FindObject
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR findme;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_FindUData
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint udata;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_GetConfigItem
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public uint id;
	public APTR storage;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_GetUData
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public uint udata;
	public uint attr;
	public APTR storage;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Import
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR dataspace;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_KillNotify
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint TrigAttr;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_KillNotifyObj
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public uint TrigAttr;
	public APTR dest;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_MultiSet
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public uint attr;
	public uint val;
	public APTR obj;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_NoNotifySet
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public uint attr;
	public uint val;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Notify
{
	public const uint AbiSize = 20;
	public uint MethodID;
	public uint TrigAttr;
	public uint TrigVal;
	public APTR DestObj;
	public uint FollowParams;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Set
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public uint attr;
	public uint val;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_SetAsString
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public uint attr;
	public APTR format;
	public uint val;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_SetUData
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public uint udata;
	public uint attr;
	public uint val;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_SetUDataOnce
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public uint udata;
	public uint attr;
	public uint val;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_WriteLong
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public uint val;
	public APTR memory;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_WriteString
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR str;
	public APTR memory;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Family_AddHead
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR obj;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Family_AddTail
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR obj;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Family_DoChildMethods
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Family_GetChild
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public int nr;
	public APTR @ref;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Family_Insert
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR obj;
	public APTR pred;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Family_Remove
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR obj;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public unsafe struct MUIP_Family_Reorder
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR after;
	public fixed uint array[1];
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public unsafe struct MUIP_Family_Sort
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public fixed uint obj[1];
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Family_Transfer
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR family;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Menustrip_ExitChange
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Menustrip_InitChange
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Menustrip_Popup
{
	public const uint AbiSize = 20;
	public uint MethodID;
	public APTR parent;
	public uint flags;
	public int x;
	public int y;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Menustrip_WillOpen
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Application_AboutMUI
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR refwindow;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Application_AddInputHandler
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR ihnode;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Application_BuildSettingsPanel
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint number;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Application_CheckRefresh
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Application_DefaultConfigItem
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint cfgid;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Application_GetMenuCheck
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint MenuID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Application_GetMenuState
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint MenuID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Application_Input
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR signal;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Application_InputBuffered
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Application_Load
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR name;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Application_NewInput
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR signal;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Application_OpenConfigWindow
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public uint flags;
	public APTR classid;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Application_PushMethod
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR dest;
	public int count;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Application_RemInputHandler
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR ihnode;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Application_ReturnID
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint retid;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Application_Run
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Application_Save
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR name;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Application_SetConfigItem
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public uint item;
	public APTR data;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Application_SetMenuCheck
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public uint MenuID;
	public int stat;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Application_SetMenuState
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public uint MenuID;
	public int stat;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Application_ShowHelp
{
	public const uint AbiSize = 20;
	public uint MethodID;
	public APTR window;
	public APTR name;
	public APTR node;
	public int line;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Application_UnpushMethod
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public APTR targetobj;
	public uint methodid;
	public uint method;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Window_AddEventHandler
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR ehnode;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Window_Cleanup
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Window_GetMenuCheck
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint MenuID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Window_GetMenuState
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint MenuID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Window_RemEventHandler
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR ehnode;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Window_ScreenToBack
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Window_ScreenToFront
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public unsafe struct MUIP_Window_SetCycleChain
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public fixed uint obj[1];
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Window_SetMenuCheck
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public uint MenuID;
	public int stat;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Window_SetMenuState
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public uint MenuID;
	public int stat;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Window_Setup
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Window_Snapshot
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public int flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Window_ToBack
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Window_ToFront
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_AskMinMax
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR MinMaxInfo;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Backfill
{
	public const uint AbiSize = 32;
	public uint MethodID;
	public int left;
	public int top;
	public int right;
	public int bottom;
	public int xoffset;
	public int yoffset;
	public int brightness;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_CheckShortHelp
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public APTR help;
	public int mx;
	public int my;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Cleanup
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_CloseCustomFont
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR font;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_ContextMenuAdd
{
	public const uint AbiSize = 24;
	public uint MethodID;
	public APTR menustrip;
	public int mx;
	public int my;
	public APTR mxp;
	public APTR myp;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_ContextMenuBuild
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public int mx;
	public int my;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_ContextMenuChoice
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR item;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_CreateBubble
{
	public const uint AbiSize = 20;
	public uint MethodID;
	public int x;
	public int y;
	public APTR txt;
	public uint flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_CreateDragImage
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public int touchx;
	public int touchy;
	public uint flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_CreateShortHelp
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public int mx;
	public int my;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_DeleteBubble
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR bubble;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_DeleteDragImage
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR di;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_DeleteShortHelp
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR help;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_DoDrag
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public int touchx;
	public int touchy;
	public uint flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_DragBegin
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR obj;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_DragDrop
{
	public const uint AbiSize = 20;
	public uint MethodID;
	public APTR obj;
	public int x;
	public int y;
	public uint qualifier;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_DragEvent
{
	public const uint AbiSize = 32;
	public uint MethodID;
	public APTR objwindow;
	public APTR obj;
	public APTR di;
	public APTR imsg;
	public int muikey;
	public uint mouseptrtype;
	public uint flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_DragFinish
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR obj;
	public int dropfollows;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_DragQuery
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR obj;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_DragReport
{
	public const uint AbiSize = 24;
	public uint MethodID;
	public APTR obj;
	public int x;
	public int y;
	public int update;
	public uint qualifier;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Draw
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_DrawBackground
{
	public const uint AbiSize = 32;
	public uint MethodID;
	public int left;
	public int top;
	public int width;
	public int height;
	public int xoffset;
	public int yoffset;
	public int flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_ExitResize
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_GoActive
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_GoInactive
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_HandleEvent
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public APTR imsg;
	public int muikey;
	public APTR ehn;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_HandleInput
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR imsg;
	public int muikey;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hide
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_InitResize
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Layout
{
	public const uint AbiSize = 24;
	public uint MethodID;
	public int left;
	public int top;
	public int width;
	public int height;
	public uint flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_OpenCustomFont
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR spec;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Relayout
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Setup
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR RenderInfo;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Show
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR clip;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Text
{
	public const uint AbiSize = 36;
	public uint MethodID;
	public int left;
	public int top;
	public int width;
	public int height;
	public APTR text;
	public int len;
	public APTR preparse;
	public uint flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_TextDim
{
	public const uint AbiSize = 20;
	public uint MethodID;
	public APTR text;
	public int len;
	public APTR preparse;
	public uint flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public unsafe struct MUIP_UpdateConfig
{
	public const uint AbiSize = 332;
	public uint MethodID;
	public uint cfgid;
	public int redrawcount;
	public fixed uint redrawobj[64];
	public fixed byte redrawflags[64];
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Prop_Decrease
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public int amount;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Prop_Increase
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public int amount;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Numeric_Decrease
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public int amount;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Numeric_Increase
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public int amount;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Numeric_ScaleToValue
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public int scalemin;
	public int scalemax;
	public int scale;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Numeric_SetDefault
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Numeric_Stringify
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public int value;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Numeric_ValueToScale
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public int scalemin;
	public int scalemax;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Pendisplay_SetColormap
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public int colormap;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Pendisplay_SetMUIPen
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public int muipen;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Pendisplay_SetRGB
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public uint red;
	public uint green;
	public uint blue;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Group_AddHead
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR obj;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Group_AddTail
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR obj;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Group_ExitChange
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Group_ExitChange2
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Group_InitChange
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Group_MoveMember
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR o;
	public int pos;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Group_Remove
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR obj;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public unsafe struct MUIP_Group_Reorder
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR after;
	public fixed uint array[1];
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public unsafe struct MUIP_Group_Sort
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public fixed uint obj[1];
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_List_Clear
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_List_Compare
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public APTR entry1;
	public APTR entry2;
	public uint column;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_List_Construct
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR entry;
	public APTR pool;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_List_CreateEditObject
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public int row;
	public int column;
	public APTR entry;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_List_CreateImage
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR obj;
	public uint flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_List_DeleteImage
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR listimg;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_List_Destruct
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR entry;
	public APTR pool;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_List_Display
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public APTR entry;
	public APTR array;
	public int row;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_List_Edit
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public int row;
	public int column;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_List_EditDone
{
	public const uint AbiSize = 20;
	public uint MethodID;
	public int row;
	public int column;
	public APTR entry;
	public APTR editobj;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_List_EndEdit
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint mode;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_List_Exchange
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public int pos1;
	public int pos2;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_List_GetEntry
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public int pos;
	public APTR entry;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_List_Insert
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public APTR entries;
	public int count;
	public int pos;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_List_InsertSingle
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR entry;
	public int pos;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_List_Jump
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public int pos;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_List_Move
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public int from;
	public int to;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_List_NextSelected
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR pos;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_List_Redraw
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public int pos;
	public APTR entry;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_List_Remove
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public int pos;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_List_Select
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public int pos;
	public int seltype;
	public APTR state;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_List_Sort
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_List_SortEntries
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR entries;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_List_TestPos
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public int x;
	public int y;
	public APTR res;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Floattext_Append
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR Text;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Dirlist_Rename
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public int row;
	public APTR newname;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Dirlist_ReRead
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Dirlist_SetComment
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public int row;
	public APTR comment;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Dirlist_SetProtection
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public int row;
	public uint flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Mccprefs_ConfigToGadgets
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR configdata;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Mccprefs_GadgetsToConfig
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR configdata;
	public APTR originator;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Mccprefs_RegisterGadget
{
	public const uint AbiSize = 28;
	public uint MethodID;
	public APTR gadget;
	public uint id;
	public uint @params;
	public APTR title;
	public uint attr;
	public APTR label;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Settingsgroup_ConfigToGadgets
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR configdata;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Settingsgroup_GadgetsToConfig
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR configdata;
	public APTR originator;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Popstring_Close
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public int result;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Popstring_Open
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Semaphore_Attempt
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Semaphore_AttemptShared
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Semaphore_Obtain
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Semaphore_ObtainShared
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Semaphore_Release
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Dataspace_Add
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public APTR data;
	public int len;
	public uint id;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Dataspace_Clear
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Dataspace_Find
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint id;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Dataspace_Get
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public uint id;
	public APTR size;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Dataspace_Merge
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR dataspace;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Dataspace_ReadIFF
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR handle;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Dataspace_Remove
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint id;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Dataspace_WriteIFF
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public APTR handle;
	public uint type;
	public uint id;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Panel_Run
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR app;
	public APTR win;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Filepanel_AddRow
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR label;
	public APTR contents;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Process_Kill
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public int maxdelay;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Process_Launch
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Process_Process
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR kill;
	public APTR proc;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Process_Signal
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint sigs;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Title_Close
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR tito;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Title_FindPage
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR titlebutton;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Title_New
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Switchpanel_Create
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR switchitem;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Switchitem_Create
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Datamap_Clear
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Datamap_Find
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR key;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Datamap_Get
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR key;
	public APTR size;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Datamap_Iterate
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR counter;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Datamap_IterationKey
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR counter;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Datamap_Remove
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR key;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Datamap_Set
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public APTR data;
	public int len;
	public APTR key;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Slave_Cleanup
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Slave_Dispatch
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public uint flags;
	public int count;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Slave_Error
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR FailedDispatch;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Slave_Setup
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Slave_SignalsReceived
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint sigmask;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Objectmap_Clear
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Objectmap_Find
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR key;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Objectmap_Iterate
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR counter;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Objectmap_IterationKey
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR counter;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Objectmap_Remove
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR key;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Objectmap_Set
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR o;
	public APTR key;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_ExternalEdit
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinputscroll_Inform
{
	public const uint AbiSize = 32;
	public uint MethodID;
	public uint xo;
	public uint yo;
	public uint xs;
	public uint ys;
	public uint xv;
	public uint yv;
	public uint noedit;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinputmcp_GrabCols
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint notall;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_Blink
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_SaveToFile
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR filename;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_LoadFromFile
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR filename;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_ExternalEditDone
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint changed;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoRevert
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoDelLine
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoCutLine
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoMarkStart
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoMarkAll
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoCut
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoCopyCut
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoCopy
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoPaste
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_AppendText
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR text;
	public int len;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinputmcp_LAct
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint which;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinputmcp_LCopy
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinputmcp_LAdd
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoToggleWordwrap
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_Acknowledge
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR contents;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_TranslateEvent
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public APTR ie;
	public APTR mappedstring;
	public APTR mappedlen;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_InsertText
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR text;
	public int len;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoLeft
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoRight
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoUp
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoDown
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoLineStart
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoLineEnd
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoTop
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoBottom
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoPageUp
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoPageDown
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoPopup
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoPrevWord
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoNextWord
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoDel
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoDelEOL
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoBS
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoBSSOL
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoubleClick
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public uint xp;
	public uint yp;
	public uint cnt;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoDelWord
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoBSWord
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoInsertFile
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_InsertFromFile
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR filename;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_HandleChar
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public uint ch;
	public uint quiet;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_HandleURL
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR url;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_HandleRexxSignal
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_HandleMisspell
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public APTR word;
	public APTR pos;
	public APTR correction;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoToggleCase
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoToggleCaseEOW
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoIncrementDec
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoDecrementDec
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinputmcp_DefaultKeys
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoUndo
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoRedo
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoTab
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoNextGadget
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoSetBookmark1
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoSetBookmark2
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoSetBookmark3
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoGotoBookmark1
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoGotoBookmark2
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Textinput_DoGotoBookmark3
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Busy_Move
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Calendar_ReadSystemDate
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Calendar_GetDaysInMonth
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public uint Month;
	public uint Year;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Calendar_Notification
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public uint NotificationMode;
	public APTR CalendarDate;
	public uint EventID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Calltips_SetRectangle
{
	public const uint AbiSize = 20;
	public uint id;
	public int MinX;
	public int MinY;
	public int MaxX;
	public int MaxY;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Chart_ClearGroup
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint GroupNumber;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Chart_GetGroup
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public uint GroupNumber;
	public APTR Label;
	public APTR Values;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Chart_InsertGroup
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public uint GroupNumber;
	public APTR Label;
	public APTR Values;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Chart_GetMinMax
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR MinimumValue;
	public APTR MaximumValue;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Chart_RemoveGroup
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint GroupNumber;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Chart_ReplaceInGroup
{
	public const uint AbiSize = 20;
	public uint MethodID;
	public uint GroupNumber;
	public uint Index;
	public uint Count;
	public APTR NewValue;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Chart_SetMax
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR MaximumValue;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Clock_OffsetFromTime
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public int hour;
	public int min;
	public int sec;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Cpumonitor_Clone
{
	public const uint AbiSize = 8;
	public uint methodid;
	public APTR target;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Graph_AddEntry
{
	public const uint AbiSize = 12;
	public uint methodid;
	public uint value;
	public uint value_back;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Graph_Reset
{
	public const uint AbiSize = 4;
	public uint methodid;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Graph_Clone
{
	public const uint AbiSize = 8;
	public uint methodid;
	public APTR target;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hex_Read
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public APTR Offset;
	public APTR Output;
	public uint Size;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hex_Write
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public APTR Offset;
	public APTR ModifiedBytes;
	public uint Count;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hex_Load
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR file;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hex_LoadMemory
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public APTR Memory;
	public uint Length;
	public uint Copy;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hex_LoadAbstract
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR Length;
	public APTR DisplayOffset;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hex_AbstractDataChanged
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR Offset;
	public APTR Length;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hex_AddAnnotation
{
	public const uint AbiSize = 20;
	public uint MethodID;
	public APTR Offset;
	public APTR EndOffset;
	public uint xRGB;
	public uint UniqueID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hex_RemoveAnnotation
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint UniqueID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hex_GetMessageForAnnotation
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint UniqueID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hex_ShowAnnotation
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint UniqueID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hex_GetMarked
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR Offset;
	public APTR EndOffset;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hex_SetMarked
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public APTR Offset;
	public APTR EndOffset;
	public uint SuppressNotification;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hex_GetCursor
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR CursorPosition;
	public APTR BytesAtCursor;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hex_SetCursor
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR CursorPosition;
	public uint SuppressNotification;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hex_GetCursorBytes
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR BytesAtCursor;
	public uint ByteCount;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hex_GetLength
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR Length;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hex_HitTest
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public int X;
	public int Y;
	public APTR Offset;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hex_SetVisibleOffset
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR Offset;
	public uint SuppressNotification;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hex_GetVisibleOffset
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR Offset;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hex_ReadData
{
	public const uint AbiSize = 20;
	public uint MethodID;
	public APTR Offset;
	public APTR Output;
	public uint Size;
	public uint ReplyMethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hex_ReadDataCompleted
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public int Size;
	public uint ReplyMethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hex_ReadDataReply
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint Size;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hex_Edit
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public APTR Offset;
	public APTR Data;
	public uint Size;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hyperlink_Follow
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hyperlink_Copy
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint CliboardUnit;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hyperlink_Encode
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR InputString;
	public APTR OutputBuffer;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Hyperlink_Decode
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR InputString;
	public APTR OutputBuffer;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Lamp_SetRGB
{
	public const uint AbiSize = 16;
	public uint mid;
	public uint red;
	public uint green;
	public uint blue;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Listtree_Close
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public APTR ListNode;
	public APTR TreeNode;
	public uint Flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Listtree_Exchange
{
	public const uint AbiSize = 24;
	public uint MethodID;
	public APTR ListNode1;
	public APTR TreeNode1;
	public APTR ListNode2;
	public APTR TreeNode2;
	public uint Flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Listtree_FindName
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public APTR ListNode;
	public APTR Name;
	public uint Flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Listtree_GetEntry
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public APTR Node;
	public int Position;
	public uint Flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Listtree_GetNr
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR TreeNode;
	public uint Flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Listtree_Insert
{
	public const uint AbiSize = 24;
	public uint MethodID;
	public APTR Name;
	public APTR User;
	public APTR ListNode;
	public APTR PrevNode;
	public uint Flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Listtree_Move
{
	public const uint AbiSize = 24;
	public uint MethodID;
	public APTR OldListNode;
	public APTR OldTreeNode;
	public APTR NewListNode;
	public APTR NewTreeNode;
	public uint Flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Listtree_Open
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public APTR ListNode;
	public APTR TreeNode;
	public uint Flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Listtree_Remove
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public APTR ListNode;
	public APTR TreeNode;
	public uint Flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Listtree_Rename
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public APTR TreeNode;
	public APTR NewName;
	public uint Flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Listtree_SetDropMark
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public int Entry;
	public uint Values;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Listtree_Sort
{
	public const uint AbiSize = 12;
	public uint MethodID;
	public APTR ListNode;
	public uint Flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Listtree_TestPos
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public int X;
	public int Y;
	public APTR Result;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIS_Listtree_TreeNode
{
	public const uint AbiSize = 18;
	public int tn_Private1;
	public int tn_Private2;
	public APTR tn_Name;
	public ushort tn_Flags;
	public APTR tn_User;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIS_Listtree_TestPos_Result
{
	public const uint AbiSize = 12;
	public APTR tpr_TreeNode;
	public ushort tpr_Flags;
	public int tpr_ListEntry;
	public ushort tpr_ListFlags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Piano_KeyEvent
{
	public const uint AbiSize = 12;
	public uint methodid;
	public int key;
	public int status;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_PowerTerm_Write
{
	public const uint AbiSize = 12;
	public uint methodid;
	public APTR data;
	public uint length;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_PowerTerm_OutFlush
{
	public const uint AbiSize = 4;
	public uint methodid;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_PowerTerm_Reset
{
	public const uint AbiSize = 4;
	public uint methodid;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_PowerTerm_SelectToClip
{
	public const uint AbiSize = 8;
	public uint methodid;
	public uint unit;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_PowerTerm_PasteFromClip
{
	public const uint AbiSize = 8;
	public uint methodid;
	public uint unit;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_PowerTerm_SavePlain
{
	public const uint AbiSize = 8;
	public uint methodid;
	public APTR filename;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_PowerTerm_SaveStyle
{
	public const uint AbiSize = 8;
	public uint methodid;
	public APTR filename;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_PowerTerm_SetAbsXY
{
	public const uint AbiSize = 12;
	public uint methodid;
	public uint cols;
	public uint rows;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_PowerTerm_SavePlainFH
{
	public const uint AbiSize = 8;
	public uint methodid;
	public uint fh;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_PowerTerm_SaveStyleFH
{
	public const uint AbiSize = 8;
	public uint methodid;
	public uint fh;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_PowerTerm_FlushReview
{
	public const uint AbiSize = 4;
	public uint methodid;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_PowerTerm_Scroll
{
	public const uint AbiSize = 12;
	public uint methodid;
	public int offset;
	public uint mode;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_PowerTerm_AddOut
{
	public const uint AbiSize = 12;
	public uint methodid;
	public APTR data;
	public uint length;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_PowerTerm_WriteUnicode
{
	public const uint AbiSize = 16;
	public uint methodid;
	public APTR data;
	public uint length;
	public uint format;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_PowerTerm_Search
{
	public const uint AbiSize = 16;
	public uint methodid;
	public APTR searchstring;
	public uint mode;
	public uint flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_PowerTerm_Duplicate
{
	public const uint AbiSize = 4;
	public uint methodid;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_PowerTerm_Select
{
	public const uint AbiSize = 8;
	public uint methodid;
	public uint selecttype;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUI_RawimageData
{
	public const uint AbiSize = 16;
	public uint ri_Width;
	public uint ri_Height;
	public uint ri_Format;
	public uint ri_Size;
	public const uint ri_DataOffset = 16;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Scintilla_Command
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public int iMessage;
	public int wParam;
	public int lParam;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Scintilla_RexxCommand
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public APTR rxmsg;
	public APTR args;
	public APTR resultptr;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Scintilla_CallTip
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint mousepointer;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Scintilla_AutoComplete
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint autopopup;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Scintilla_BindWithProjectIndex
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public APTR ProjectIndex;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Scintilla_RefreshProjectIndex
{
	public const uint AbiSize = 4;
	public uint MethodID;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Scintilla_ContextMenuAdd
{
	public const uint AbiSize = 16;
	public uint MethodID;
	public APTR ContextMenu;
	public uint x;
	public uint y;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Urltext_OpenURL
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint Flags;
}

[StructLayout(LayoutKind.Sequential, Pack = 2)]
public struct MUIP_Urltext_Copy
{
	public const uint AbiSize = 8;
	public uint MethodID;
	public uint ClipboardUnit;
}
