/*
- Copyright (C) 2026 Ilkka Lehtoranta
- SPDX-License-Identifier: MIT
 */

using System.Collections.ObjectModel;

namespace CopperSharp.Compiler;

/// <summary>Motorola CPU selected for generated code.</summary>
public enum M68kCpuTarget
{
	M68000,
	M68020,
	M68040,
	M68060
}

/// <summary>Floating-point implementation selected for generated code.</summary>
public enum M68kFloatingPointMode
{
	/// <summary>Reject managed floating-point values and emit no FPU instructions.</summary>
	Disabled,

	/// <summary>Use the integrated MC68040/MC68060 floating-point unit.</summary>
	M68040,

	/// <summary>Use an external MC68882 coprocessor with an MC68020 host CPU.</summary>
	M68882,

	/// <summary>Use the compiler's bundled integer-only CopperFloat runtime.</summary>
	SoftFloat
}

/// <summary>Policy for using the memory-writing <c>CLR</c> instruction.</summary>
public enum M68kClrPolicy
{
	/// <summary>
	/// Use CLR for isolated compiler-owned clears where materializing zero is not
	/// faster, and for general memory on CPUs without MC68000 read-before-write.
	/// </summary>
	Auto = 0,

	/// <summary>Use CLR even for MC68000-compatible targets.</summary>
	Always = 2
}

/// <summary>Container generated by the linker.</summary>
public enum M68kOutputFormat
{
	Hunk,
	KickstartRom,
	Assembly
}

/// <summary>High-level runtime assumptions selected for the generated image.</summary>
public enum M68kRuntimeProfile
{
	/// <summary>No post-entry lifetime or shutdown contract is assumed.</summary>
	Freestanding,

	/// <summary>
	/// The selected entry is invoked once as an application and its private
	/// image storage becomes unobservable when the entry terminates.
	/// </summary>
	Application,

	/// <summary>The generated image is persistent and may be entered again.</summary>
	Rom
}

/// <summary>Managed heap policy used by generated allocation instructions.</summary>
public enum M68kMemoryManagement
{
	None,
	ExternalAllocator,
	BumpAllocator,
	ManagedPoolMarkSweepGc,
	ExecPoolMarkSweepGc,
}

/// <summary>When a linked managed runtime should run mark/sweep collection.</summary>
public enum M68kGcSweepStrategy
{
	OnDemand,
	OnAllocationFailure,
	EveryAllocation,
	TelemetryTriggered
}

/// <summary>Managed exception behavior selected for generated code.</summary>
public enum M68kExceptionMode
{
	/// <summary>Use the table-driven managed exception runtime.</summary>
	Full,

	/// <summary>Preserve the legacy non-returning fault behavior.</summary>
	Yolo
}

/// <summary>Physical 68k register used by an imported or exported ABI.</summary>
public enum M68kRegister
{
	D0,
	D1,
	D2,
	D3,
	D4,
	D5,
	D6,
	D7,
	A0,
	A1,
	A2,
	A3,
	A4,
	A5,
	A6
}

/// <summary>Physical floating-point register used by a native FPU ABI.</summary>
public enum M68kFpuRegister
{
	FP0,
	FP1,
	FP2,
	FP3,
	FP4,
	FP5,
	FP6,
	FP7
}

/// <summary>How a platform extension supplies a base register for an external call.</summary>
public enum M68kExternalBaseSource
{
	CachedPointer,
	WritableSlot,
	Immediate
}

/// <summary>How an external call reports a managed failure.</summary>
public enum M68kExternalExceptionPolicy
{
	/// <summary>The call has no compiler-visible exception status.</summary>
	None,

	/// <summary>A nonzero value in the configured status register raises.</summary>
	NonZeroStatus
}

/// <summary>A decoded metadata attribute supplied to an optional platform resolver.</summary>
public sealed record M68kMetadataAttribute(
	string TypeName,
	IReadOnlyList<object?> FixedArguments);

/// <summary>Architecture-neutral metadata for an external method declaration.</summary>
public sealed record M68kExternalMethod(
	string AssemblyName,
	string DisplayName,
	string DeclaringTypeName,
	string Name,
	bool IsStatic,
	IReadOnlyList<M68kMetadataAttribute> DeclaringTypeAttributes,
	IReadOnlyList<M68kMetadataAttribute> MethodAttributes,
	IReadOnlyList<IReadOnlyList<M68kMetadataAttribute>> ParameterAttributes,
	IReadOnlyList<M68kMetadataAttribute> ReturnAttributes);

/// <summary>Describes one base-relative external call without platform-specific terminology.</summary>
public sealed record M68kExternalCallConvention(
	string Identity,
	M68kExternalBaseSource BaseSource,
	M68kRegister BaseRegister,
	short Displacement,
	M68kRegister? CacheRegister = null,
	uint SourceAddress = 0,
	uint InitialValue = 0,
	string? SlotSymbol = null,
	IReadOnlyList<M68kRegister>? ParameterRegisters = null,
	M68kRegister ReturnRegister = M68kRegister.D0,
	M68kExternalExceptionPolicy ExceptionPolicy = M68kExternalExceptionPolicy.None,
	M68kRegister? ExceptionStatusRegister = null);

/// <summary>Optional target-platform metadata and call-convention resolver.</summary>
public interface IM68kExternalCallResolver
{
	bool TryResolve(
		M68kExternalMethod method,
		out M68kExternalCallConvention convention);
}

/// <summary>Well-known hooks used by generated managed-runtime operations.</summary>
public static class M68kRuntimeImports
{
	/// <summary>Target marker enabling the built-in Amiga unhandled-exception requester.</summary>
	public const string AmigaUnhandledExceptionRequester =
		"__c68k_amiga_unhandled_exception_requester";

	/// <summary>Target marker enabling an Exec-owned arena for the built-in managed pool.</summary>
	public const string AmigaManagedPoolArena =
		"__c68k_amiga_managed_pool_arena";

	/// <summary>
	/// Allocates a zero-filled object block. The requested byte count is passed in
	/// D0 and the address is returned in D0.
	/// </summary>
	public const string Allocate = "__c68k_alloc";

	/// <summary>Non-returning handler used for null, bounds, and runtime failures.</summary>
	public const string Fail = "__c68k_fail";

	/// <summary>
	/// Optional last-chance exception hook. A0 contains the exception object and
	/// D0 contains the compiler runtime reason code. Returning continues to the
	/// target's unhandled-exception action.
	/// </summary>
	public const string UnhandledException = "__c68k_unhandled_exception";

	/// <summary>
	/// Explicitly releases a managed allocation slot. The address of a four-byte
	/// reference slot is passed in A0. Runtime code may free
	/// the allocation and should clear the slot to zero.
	/// </summary>
	public const string Dispose = "__c68k_dispose";

	/// <summary>Initializes a linked managed runtime before the managed entry point.</summary>
	public const string GcInit = "__c68k_gc_init";

	/// <summary>
	/// Runs an explicit managed collection cycle. D0 contains the address of the
	/// suspended return-PC slot, D1 the resume PC, A0 the generated method table,
	/// and A1 the static-root table.
	/// </summary>
	public const string GcCollect = "__c68k_gc_collect";

	/// <summary>Returns the runtime's approximate stale-pressure byte count.</summary>
	public const string GcGetStaleBytes = "__c68k_gc_get_stale_bytes";

	/// <summary>Returns the runtime's approximate stale-pressure block count.</summary>
	public const string GcGetStaleBlocks = "__c68k_gc_get_stale_blocks";

	/// <summary>Shuts down a linked managed runtime after the managed entry point.</summary>
	public const string GcShutdown = "__c68k_gc_shutdown";
}

/// <summary>Marks the managed method used as the image entry point.</summary>
[AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
public sealed class M68kEntryPointAttribute : Attribute
{
}

/// <summary>Publishes a managed method under a linker symbol.</summary>
[AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
public sealed class M68kExportAttribute : Attribute
{
	public M68kExportAttribute(string? name = null)
	{
		Name = name;
	}

	public string? Name { get; }
}

/// <summary>Declares a method whose implementation is supplied by the link environment.</summary>
[AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
public sealed class M68kImportAttribute : Attribute
{
	public M68kImportAttribute(string name)
	{
		ArgumentException.ThrowIfNullOrWhiteSpace(name);
		Name = name;
	}

	public string Name { get; }
}

/// <summary>Maps a parameter or return value to a physical 68k register.</summary>
[AttributeUsage(AttributeTargets.Parameter | AttributeTargets.ReturnValue, AllowMultiple = false)]
public sealed class M68kRegisterAttribute : Attribute
{
	public M68kRegisterAttribute(M68kRegister register)
	{
		Register = register;
	}

	public M68kRegister Register { get; }
}

/// <summary>Maps a floating-point parameter or return value to an FPU register.</summary>
[AttributeUsage(AttributeTargets.Parameter | AttributeTargets.ReturnValue, AllowMultiple = false)]
public sealed class M68kFpuRegisterAttribute : Attribute
{
	public M68kFpuRegisterAttribute(M68kFpuRegister register)
	{
		Register = register;
	}

	public M68kFpuRegister Register { get; }
}

/// <summary>
/// Marks a value type used solely as caller-provided storage for an external
/// routine that initializes the pointed-to buffer before it is read.
///
/// Locals of this type are intentionally not initialized by generated code.
/// Do not use this attribute for ordinary managed values or structures whose
/// default state is observable.
/// </summary>
[AttributeUsage(AttributeTargets.Struct, AllowMultiple = false)]
public sealed class M68kUninitializedStorageAttribute : Attribute
{
}

/// <summary>Marks a pointer parameter whose complete caller-owned buffer is populated on success.</summary>
[AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false)]
public sealed class M68kWritesEntireBufferAttribute : Attribute
{
}

/// <summary>Marks a pointer parameter that receives output bytes or elements.</summary>
[AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false)]
public sealed class M68kWritesBufferAttribute : Attribute
{
}

/// <summary>Requests the specified alignment for the address of a stack local.</summary>
[AttributeUsage(AttributeTargets.Struct, AllowMultiple = false)]
public sealed class M68kStackAlignmentAttribute : Attribute
{
	public M68kStackAlignmentAttribute(int alignment)
	{
		if (alignment < 2 || (alignment & (alignment - 1)) != 0)
		{
			throw new ArgumentOutOfRangeException(nameof(alignment));
		}

		Alignment = alignment;
	}

	public int Alignment { get; }
}

/// <summary>Options for an Amiga loadable HUNK executable.</summary>
public sealed record HunkOutputOptions
{
	/// <summary>Include HUNK_SYMBOL records for compiled methods.</summary>
	public bool IncludeSymbols { get; init; } = true;
}

/// <summary>Options for a Kickstart-compatible ROM image.</summary>
public sealed record KickstartRomOutputOptions
{
	/// <summary>ROM size. Version one accepts 256 KiB or 512 KiB.</summary>
	public int Size { get; init; } = 512 * 1024;

	/// <summary>Initial supervisor stack pointer copied into reset vector zero.</summary>
	public uint InitialStackPointer { get; init; } = 0x0008_0000;

	/// <summary>Byte used for unused ROM space.</summary>
	public byte FillByte { get; init; } = 0xFF;

	/// <summary>
	/// Optional physical base. Zero selects the standard top-of-24-bit-space address
	/// derived from <see cref="Size"/>.
	/// </summary>
	public uint BaseAddress { get; init; }
}

/// <summary>Options for runtime-managed heap backends.</summary>
public sealed record M68kHeapOptions
{
	/// <summary>
	/// Start address for the compiler runtime's managed pool. Zero means
	/// startup/runtime code must provide the heap range.
	/// </summary>
	public uint StartAddress { get; init; }

	/// <summary>
	/// Heap size for the compiler runtime's managed pool. Zero means
	/// startup/runtime code must provide the heap range.
	/// </summary>
	public uint Size { get; init; }
}

/// <summary>Options for approximate stale-pressure telemetry in GC runtimes.</summary>
public sealed record M68kGcTelemetryOptions
{
	/// <summary>Approximate stale-pressure bytes that should make allocation trigger GC.</summary>
	public uint StaleBytesThreshold { get; init; }

	/// <summary>Approximate stale-pressure block count that should make allocation trigger GC.</summary>
	public uint StaleBlocksThreshold { get; init; }

	/// <summary>Runtime-defined telemetry sampling interval. Zero selects runtime default.</summary>
	public ushort IntervalTicks { get; init; }
}

/// <summary>Closed-world compilation request.</summary>
public sealed record M68kCompilationRequest
{
	public required string AssemblyPath { get; init; }

	/// <summary>
	/// Additional managed assemblies whose IL method bodies may enter the closed-world
	/// compilation graph. Other references remain metadata-only platform dependencies.
	/// </summary>
	public IReadOnlyList<string> ManagedAssemblyPaths { get; init; } = Array.Empty<string>();

	/// <summary>
	/// Entry selector in <c>Namespace.Type::Method</c> form. When omitted, exactly one
	/// method carrying <see cref="M68kEntryPointAttribute"/> must exist.
	/// </summary>
	public string? EntryPoint { get; init; }

	public M68kCpuTarget Cpu { get; init; } = M68kCpuTarget.M68000;

	/// <summary>
	/// Selects native FPU or bundled software floating-point code generation.
	/// Disabled preserves the historical integer-only compiler behavior.
	/// </summary>
	public M68kFloatingPointMode FloatingPoint { get; init; } =
		M68kFloatingPointMode.Disabled;

	/// <summary>
	/// Controls memory clears. Auto accounts for the MC68000 CLR read cycle: it
	/// reuses an available zero register with MOVE, permits isolated CLR clears of
	/// compiler-owned memory when MOVEQ plus MOVE would not be faster, and enables
	/// CLR for general memory on MC68020 and newer targets. Always explicitly opts
	/// MC68000-compatible general memory into CLR's read-before-write behavior.
	/// </summary>
	public M68kClrPolicy ClrPolicy { get; init; } = M68kClrPolicy.Auto;

	public M68kOutputFormat OutputFormat { get; init; } = M68kOutputFormat.Hunk;

	public M68kRuntimeProfile RuntimeProfile { get; init; } =
		M68kRuntimeProfile.Freestanding;

	/// <summary>
	/// Selects managed exception behavior. Full mode is the default; YOLO is an
	/// explicit compatibility mode for images that retain fatal runtime faults.
	/// </summary>
	public M68kExceptionMode ExceptionMode { get; init; } = M68kExceptionMode.Full;

	/// <summary>
	/// Managed heap policy. When omitted, ROM profile uses no managed heap and
	/// other profiles use the external <see cref="M68kRuntimeImports.Allocate"/>
	/// hook.
	/// </summary>
	public M68kMemoryManagement? MemoryManagement { get; init; }

	/// <summary>
	/// GC sweep trigger. When omitted, GC backends use
	/// <see cref="M68kGcSweepStrategy.OnAllocationFailure"/>.
	/// </summary>
	public M68kGcSweepStrategy? GcSweepStrategy { get; init; }

	public M68kGcTelemetryOptions GcTelemetry { get; init; } = new();

	public M68kHeapOptions Heap { get; init; } = new();

	public HunkOutputOptions Hunk { get; init; } = new();

	public KickstartRomOutputOptions Rom { get; init; } = new();

	/// <summary>Absolute addresses for named imports.</summary>
	public IReadOnlyDictionary<string, uint> Imports { get; init; } =
		new ReadOnlyDictionary<string, uint>(new Dictionary<string, uint>());

	/// <summary>Ordered target extensions for external call conventions.</summary>
	public IReadOnlyList<IM68kExternalCallResolver> ExternalCallResolvers { get; init; } =
		Array.Empty<IM68kExternalCallResolver>();
}

/// <summary>A named range in the linked image.</summary>
public readonly record struct M68kSymbol(string Name, uint Address, int Size);

/// <summary>An absolute 32-bit address patched by the linker.</summary>
public readonly record struct M68kRelocation(int Offset, string Target);

/// <summary>Final linked footprint of one natural loop.</summary>
public sealed record M68kLoopFootprint(
	string Method,
	int HeaderIlOffset,
	uint HeaderAddress,
	int InstructionBytes,
	int SpanBytes,
	int CacheLineCount,
	bool FitsIn256ByteInstructionCache);

/// <summary>Successful compiler output.</summary>
public sealed class M68kCompilationResult
{
	internal M68kCompilationResult(
		byte[] image,
		byte[] code,
		uint entryPoint,
		IReadOnlyList<M68kSymbol> symbols,
		IReadOnlyList<M68kRelocation> relocations,
		string map,
		string? text,
		IReadOnlyList<Backend.M68kMethodAllocationStatistics>
			allocationStatistics,
		IReadOnlyList<Backend.M68kTerminalDeadStoreStatistics>
			terminalDeadStoreStatistics,
		IReadOnlyList<M68kLoopFootprint> loopFootprints,
		IReadOnlyList<string> frameworkFeatures)
	{
		Image = image;
		Code = code;
		EntryPoint = entryPoint;
		Symbols = symbols;
		Relocations = relocations;
		Map = map;
		Text = text;
		AllocationStatistics = allocationStatistics;
		TerminalDeadStoreStatistics = terminalDeadStoreStatistics;
		LoopFootprints = loopFootprints;
		FrameworkFeatures = frameworkFeatures;
	}

	public byte[] Image { get; }

	/// <summary>Linked code before its output container is applied.</summary>
	public byte[] Code { get; }

	public uint EntryPoint { get; }

	public IReadOnlyList<M68kSymbol> Symbols { get; }

	public IReadOnlyList<M68kRelocation> Relocations { get; }

	public string Map { get; }

	/// <summary>Assembler source when <see cref="M68kOutputFormat.Assembly"/> is selected.</summary>
	public string? Text { get; }

	/// <summary>
	/// Natural-loop footprints measured from final linked instruction ranges.
	/// Cache lines use the MC68020/MC68030 256-byte, four-byte-line model.
	/// </summary>
	public IReadOnlyList<M68kLoopFootprint> LoopFootprints { get; }

	/// <summary>Independently linked framework/runtime capabilities.</summary>
	public IReadOnlyList<string> FrameworkFeatures { get; }

	internal IReadOnlyList<Backend.M68kMethodAllocationStatistics>
		AllocationStatistics { get; }

	internal IReadOnlyList<Backend.M68kTerminalDeadStoreStatistics>
		TerminalDeadStoreStatistics { get; }
}
