<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1591</NoWarn>
    <PackageId>CopperSharp.Sdk.Amiga</PackageId>
    <Title>CopperSharp Amiga SDK</Title>
    <Description>Typed Amiga and MorphOS m68k ABI declarations for programs compiled with CopperSharp.</Description>
    <PackageTags>amiga;morphos;m68k;cil;aot;sdk</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Examples\**\*.cs" />
    <Compile Remove="**\GuestCodecs.cs" />
    <Compile Remove="GuestMemory\**\*.cs" />
	<Compile Remove="Utility\UtilityHookCodec.cs" />
    <Compile Include="Examples\DOS\Program.cs" />
    <Compile Include="Examples\FileStats\Program.cs" />
    <ProjectReference Include="..\Compiler\CopperSharp.Compiler.csproj" />
    <None Include="Examples\DOS\DOS.csproj" />
    <None Include="Examples\FileStats\FileStats.csproj" />
    <None Include="Examples\MUITaskList\MUITaskList.csproj" />
    <None Include="Examples\MUISunflower\MUISunflower.csproj" />
	<None Include="Hardware\README.md" Pack="true" PackagePath="Hardware\" />
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
