<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Compiler\CopperSharp.Compiler.csproj" />
    <ProjectReference Include="..\Runtime.Managed\CopperSharp.Runtime.Managed.csproj" />
    <ProjectReference Include="..\Targets.Amiga\CopperSharp.Targets.Amiga.csproj" />
  </ItemGroup>

</Project>
